### ISSUE TITLE
Windows Error

### ISSUE THREAD

**Issue by cyberpunkbln** [nicohman/gog-rs#1]
Hello,

cool library but under windows it gives an problem with the not needed linux extractor. He trys to compile the extract.rs but under windows it cause an error.

```
use std::os::unix::fs::PermissionsExt;
   |              ^^^^ could not find `unix` in `os`
```

its clear, it is possible to make an compiler switch that an windows os don't need the compiler? or you know an fake unix::fs library for that cause?

thx

**Comment by nicohman** [comment]
Whoops, I didn't even think of that. Could you try compiling the latest master and see if that works? Thanks!

**Comment by cyberpunkbln** [comment]
Hello,

yes latest github-master works without the error, problem solved, but now i have the problem with the curl library that the curl library only compiles with msvc and i use mingw64.

I search for an fully portable MSVC Distribution:), my gnu toolchain in windows are fully portable.

Thx.
